python2 makeSelectedMtuples.py FullMC/rhc_numu_x_numu_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/rhc_numu_x_nue_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/rhc_nue_x_nue_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/rhc_numubar_x_numubar_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/rhc_numubar_x_nuebar_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/rhc_nuebar_x_nuebar_wMomentumCut.root

python2 makeSelectedMtuples.py FullMC/fhc_numu_x_numu_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/fhc_numu_x_nue_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/fhc_nue_x_nue_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/fhc_numubar_x_numubar_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/fhc_numubar_x_nuebar_wMomentumCut.root
python2 makeSelectedMtuples.py FullMC/fhc_nuebar_x_nuebar_wMomentumCut.root
